name: joekky/proxmox
resources:
  proxmox_vm_qemu:
    name: proxmox_vm_qemu
    description: Manages a Proxmox Virtual Machine
    title: Proxmox Virtual Machine
    argumentDocs:
      target_node: "Target node name"
      name: "The name of the VM"
      vmid: "The ID of the VM"
